"""Locks down the current API surface (Issue #12 checklist: "existing API
endpoints не changing contract without explicit decision"). This is a
route-table snapshot, not a behavioral test: it fails whenever a route is
added, removed, or has its path/method changed, forcing that change to be a
deliberate, visible diff in this file rather than an accidental side effect
of a refactor.

Framework-internal routes (/docs, /redoc, /openapi.json) are excluded since
they're generated by FastAPI itself, not part of our API surface.
"""

from app.api.main import app

_FRAMEWORK_ROUTES = {"/docs", "/docs/oauth2-redirect", "/redoc", "/openapi.json"}

EXPECTED_ROUTES = {
    ("DELETE", "/crm/clients/{client_id}/files/{file_id}"),
    ("DELETE", "/crm/clients/{client_id}/languages/{lang_id}"),
    ("DELETE", "/crm/clients/{client_id}/skills/{skill_id}"),
    ("DELETE", "/crm/clients/{client_id}/work-experience/{we_id}"),
    ("GET", "/admin/dashboard/summary"),
    ("GET", "/admin/users"),
    ("GET", "/admin/users/{user_id}"),
    ("GET", "/admin/users/{user_id}/edit-logs"),
    ("GET", "/admin/users/{user_id}/messages"),
    ("GET", "/crm/clients"),
    ("GET", "/crm/clients/{client_id}"),
    ("GET", "/crm/clients/{client_id}/calls"),
    ("GET", "/crm/clients/{client_id}/career-consultation"),
    ("GET", "/crm/clients/{client_id}/files"),
    ("GET", "/crm/clients/{client_id}/files/{file_id}/download"),
    ("GET", "/crm/clients/{client_id}/tasks"),
    ("GET", "/crm/clients/{client_id}/timeline"),
    ("GET", "/crm/dashboard"),
    ("GET", "/crm/me"),
    ("GET", "/crm/users"),
    ("GET", "/crm/users/assignable"),
    ("GET", "/direction/clients"),
    ("GET", "/direction/clients/{user_id}/card"),
    ("GET", "/direction/clients/{user_id}/profile-status"),
    ("GET", "/direction/clients/{user_id}/publishable"),
    ("GET", "/health"),
    ("GET", "/users/{telegram_id}/messages"),
    ("GET", "/users/{telegram_id}/profile"),
    ("PATCH", "/admin/users/{user_id}/profile"),
    ("PATCH", "/admin/users/{user_id}/status"),
    ("PATCH", "/crm/clients/{client_id}"),
    ("PATCH", "/crm/clients/{client_id}/career-consultation"),
    ("PATCH", "/crm/clients/{client_id}/files/{file_id}/current-cv"),
    ("PATCH", "/crm/clients/{client_id}/profile"),
    ("PATCH", "/crm/clients/{client_id}/work-experience/{we_id}"),
    ("PATCH", "/crm/users/{staff_id}"),
    ("POST", "/admin/auth/login"),
    ("POST", "/direction/clients/{user_id}/full-pipeline"),
    ("POST", "/direction/clients/{user_id}/generate"),
    ("POST", "/direction/clients/{user_id}/profile"),
    ("POST", "/direction/runs/{run_id}/approve"),
    ("POST", "/direction/runs/{run_id}/corrections"),
    ("POST", "/direction/runs/{run_id}/critic"),
    ("POST", "/direction/runs/{run_id}/narrative"),
    ("POST", "/direction/runs/{run_id}/reject"),
    ("POST", "/direction/runs/{run_id}/request-changes"),
    ("POST", "/crm/clients"),
    ("POST", "/crm/clients/{client_id}/assign-consultant"),
    ("POST", "/crm/clients/{client_id}/assign-manager"),
    ("POST", "/crm/clients/{client_id}/calls"),
    ("POST", "/crm/clients/{client_id}/career-consultation/complete"),
    ("POST", "/crm/clients/{client_id}/files"),
    ("POST", "/crm/clients/{client_id}/languages"),
    ("POST", "/crm/clients/{client_id}/ready-for-matching"),
    ("POST", "/crm/clients/{client_id}/screening/complete"),
    ("POST", "/crm/clients/{client_id}/skills"),
    ("POST", "/crm/clients/{client_id}/status"),
    ("POST", "/crm/clients/{client_id}/tasks"),
    ("POST", "/crm/clients/{client_id}/work-experience"),
    ("POST", "/crm/tasks/{task_id}/cancel"),
    ("POST", "/crm/tasks/{task_id}/complete"),
    ("POST", "/crm/users"),
}


def _current_routes() -> set[tuple[str, str]]:
    routes = set()
    for route in app.routes:
        path = getattr(route, "path", None)
        methods = getattr(route, "methods", None)
        if path is None or not methods or path in _FRAMEWORK_ROUTES:
            continue
        for method in methods:
            if method == "HEAD":
                continue
            routes.add((method, path))
    return routes


def test_api_route_table_matches_frozen_snapshot():
    current = _current_routes()
    missing = EXPECTED_ROUTES - current
    added = current - EXPECTED_ROUTES
    assert not missing, f"routes removed or renamed since the snapshot was frozen: {sorted(missing)}"
    assert not added, (
        f"new routes not yet reflected in the frozen snapshot: {sorted(added)}. "
        "If this is an intentional API change, update EXPECTED_ROUTES in this file."
    )
