"""Locks down the current API surface (Issue #12 checklist: "existing API
endpoints не changing contract without explicit decision"). This is a
route-table snapshot, not a behavioral test: it fails whenever a route is
added, removed, or has its path/method changed, forcing that change to be a
deliberate, visible diff in this file rather than an accidental side effect
of a refactor.

Framework-internal routes (/docs, /redoc, /openapi.json) are excluded since
they're generated by FastAPI itself, not part of our API surface.
"""

from app.api.main import app

_FRAMEWORK_ROUTES = {"/docs", "/docs/oauth2-redirect", "/redoc", "/openapi.json"}

EXPECTED_ROUTES = {
    ("DELETE", "/crm/clients/{client_id}/files/{file_id}"),
    ("DELETE", "/crm/clients/{client_id}/languages/{lang_id}"),
    ("DELETE", "/crm/clients/{client_id}/skills/{skill_id}"),
    ("DELETE", "/crm/clients/{client_id}/work-experience/{we_id}"),
    ("GET", "/admin/dashboard/summary"),
    ("GET", "/admin/users"),
    ("GET", "/admin/users/{user_id}"),
    ("GET", "/admin/users/{user_id}/edit-logs"),
    ("GET", "/admin/users/{user_id}/messages"),
    ("GET", "/crm/clients"),
    ("GET", "/crm/clients/{client_id}"),
    ("GET", "/crm/clients/{client_id}/calls"),
    ("GET", "/crm/clients/{client_id}/career-consultation"),
    ("GET", "/crm/clients/{client_id}/files"),
    ("GET", "/crm/clients/{client_id}/files/{file_id}/download"),
    ("GET", "/crm/clients/{client_id}/tasks"),
    ("GET", "/crm/clients/{client_id}/timeline"),
    ("GET", "/crm/dashboard"),
    ("GET", "/crm/me"),
    ("GET", "/crm/users"),
    ("GET", "/crm/users/assignable"),
    ("GET", "/health"),
    ("GET", "/users/{telegram_id}/messages"),
    ("GET", "/users/{telegram_id}/profile"),
    ("PATCH", "/admin/users/{user_id}/profile"),
    ("PATCH", "/admin/users/{user_id}/status"),
    ("PATCH", "/crm/clients/{client_id}"),
    ("PATCH", "/crm/clients/{client_id}/career-consultation"),
    ("PATCH", "/crm/clients/{client_id}/files/{file_id}/current-cv"),
    ("PATCH", "/crm/clients/{client_id}/profile"),
    ("PATCH", "/crm/clients/{client_id}/work-experience/{we_id}"),
    ("PATCH", "/crm/users/{staff_id}"),
    ("POST", "/admin/auth/login"),
    ("POST", "/crm/clients"),
    ("POST", "/crm/clients/{client_id}/assign-consultant"),
    ("POST", "/crm/clients/{client_id}/assign-manager"),
    ("POST", "/crm/clients/{client_id}/calls"),
    ("POST", "/crm/clients/{client_id}/career-consultation/complete"),
    ("POST", "/crm/clients/{client_id}/files"),
    ("POST", "/crm/clients/{client_id}/languages"),
    ("POST", "/crm/clients/{client_id}/ready-for-matching"),
    ("POST", "/crm/clients/{client_id}/screening/complete"),
    ("POST", "/crm/clients/{client_id}/skills"),
    ("POST", "/crm/clients/{client_id}/status"),
    ("POST", "/crm/clients/{client_id}/tasks"),
    ("POST", "/crm/clients/{client_id}/work-experience"),
    ("POST", "/crm/tasks/{task_id}/cancel"),
    ("POST", "/crm/tasks/{task_id}/complete"),
    ("POST", "/crm/users"),
    # MNP V1 (MNP_DEVELOPMENT_PACKAGE_V1, app/api/mnp.py) -- Founder-directed
    # implementation, deliberate addition, not an accidental refactor side effect.
    ("GET", "/v1/mnp/career-card"),
    ("GET", "/v1/mnp/career-matches/{career_match_id}"),
    ("GET", "/v1/mnp/career-matches/{career_match_id}/route"),
    ("GET", "/v1/mnp/careers"),
    ("GET", "/v1/mnp/careers/{career_id}"),
    ("GET", "/v1/mnp/match-runs/{match_run_id}/careers"),
    ("GET", "/v1/mnp/questionnaire/missing"),
    ("POST", "/v1/mnp/documents"),
    ("POST", "/v1/mnp/match-runs"),
    ("POST", "/v1/mnp/questionnaire/career-capital"),
    ("POST", "/v1/mnp/questionnaire/career-intent"),
    ("POST", "/v1/mnp/session"),
    # MNP Career KB Editor V1 (app/api/mnp_admin.py) -- admin-only authoring
    # API. Every route requires an admin bearer token (get_current_admin).
    ("GET", "/v1/mnp/admin/careers"),
    ("GET", "/v1/mnp/admin/careers/{career_id}"),
    ("GET", "/v1/mnp/admin/careers/{career_id}/history"),
    ("GET", "/v1/mnp/admin/careers/{career_id}/publish-readiness"),
    ("GET", "/v1/mnp/admin/knowledge/search"),
    ("GET", "/v1/mnp/admin/me"),
    ("GET", "/v1/mnp/admin/skills/search"),
    ("PATCH", "/v1/mnp/admin/careers/{career_id}"),
    ("PATCH", "/v1/mnp/admin/careers/{career_id}/career-path/{row_id}"),
    ("PATCH", "/v1/mnp/admin/careers/{career_id}/external-references/{row_id}"),
    ("PATCH", "/v1/mnp/admin/careers/{career_id}/knowledge/{row_id}"),
    ("PATCH", "/v1/mnp/admin/careers/{career_id}/pros-cons/{row_id}"),
    ("PATCH", "/v1/mnp/admin/careers/{career_id}/relations/{row_id}"),
    ("PATCH", "/v1/mnp/admin/careers/{career_id}/requirements/{row_id}"),
    ("PATCH", "/v1/mnp/admin/careers/{career_id}/responsibilities/{row_id}"),
    ("PATCH", "/v1/mnp/admin/careers/{career_id}/skills/{row_id}"),
    ("POST", "/v1/mnp/admin/careers"),
    ("POST", "/v1/mnp/admin/careers/{career_id}/archive"),
    ("POST", "/v1/mnp/admin/careers/{career_id}/career-path"),
    ("POST", "/v1/mnp/admin/careers/{career_id}/career-path/{row_id}/move"),
    ("POST", "/v1/mnp/admin/careers/{career_id}/external-references"),
    ("POST", "/v1/mnp/admin/careers/{career_id}/knowledge"),
    ("POST", "/v1/mnp/admin/careers/{career_id}/pros-cons"),
    ("POST", "/v1/mnp/admin/careers/{career_id}/pros-cons/{row_id}/move"),
    ("POST", "/v1/mnp/admin/careers/{career_id}/publish"),
    ("POST", "/v1/mnp/admin/careers/{career_id}/relations"),
    ("POST", "/v1/mnp/admin/careers/{career_id}/requirements"),
    ("POST", "/v1/mnp/admin/careers/{career_id}/responsibilities"),
    ("POST", "/v1/mnp/admin/careers/{career_id}/responsibilities/{row_id}/move"),
    ("POST", "/v1/mnp/admin/careers/{career_id}/skills"),
    ("POST", "/v1/mnp/admin/careers/{career_id}/unarchive"),
    ("POST", "/v1/mnp/admin/knowledge"),
    ("POST", "/v1/mnp/admin/skills"),
    ("DELETE", "/v1/mnp/admin/careers/{career_id}/career-path/{row_id}"),
    ("DELETE", "/v1/mnp/admin/careers/{career_id}/external-references/{row_id}"),
    ("DELETE", "/v1/mnp/admin/careers/{career_id}/knowledge/{row_id}"),
    ("DELETE", "/v1/mnp/admin/careers/{career_id}/pros-cons/{row_id}"),
    ("DELETE", "/v1/mnp/admin/careers/{career_id}/relations/{row_id}"),
    ("DELETE", "/v1/mnp/admin/careers/{career_id}/requirements/{row_id}"),
    ("DELETE", "/v1/mnp/admin/careers/{career_id}/responsibilities/{row_id}"),
    ("DELETE", "/v1/mnp/admin/careers/{career_id}/skills/{row_id}"),
    # --- PERSON KB BASE V1 (app/api/person_kb.py) -- admin + user (own profile) + CV
    ("GET", "/v1/mnp/admin/persons"),
    ("POST", "/v1/mnp/admin/persons"),
    ("GET", "/v1/mnp/admin/persons/skills/search"),
    ("GET", "/v1/mnp/admin/persons/{person_id}"),
    ("PATCH", "/v1/mnp/admin/persons/{person_id}"),
    ("POST", "/v1/mnp/admin/persons/{person_id}/activate"),
    ("POST", "/v1/mnp/admin/persons/{person_id}/archive"),
    ("POST", "/v1/mnp/admin/persons/{person_id}/unarchive"),
    ("POST", "/v1/mnp/admin/persons/{person_id}/skills"),
    ("PATCH", "/v1/mnp/admin/persons/{person_id}/skills/{row_id}"),
    ("DELETE", "/v1/mnp/admin/persons/{person_id}/skills/{row_id}"),
    ("POST", "/v1/mnp/admin/persons/{person_id}/educations"),
    ("PATCH", "/v1/mnp/admin/persons/{person_id}/educations/{row_id}"),
    ("DELETE", "/v1/mnp/admin/persons/{person_id}/educations/{row_id}"),
    ("POST", "/v1/mnp/admin/persons/{person_id}/credentials"),
    ("PATCH", "/v1/mnp/admin/persons/{person_id}/credentials/{row_id}"),
    ("DELETE", "/v1/mnp/admin/persons/{person_id}/credentials/{row_id}"),
    ("POST", "/v1/mnp/admin/persons/{person_id}/experiences"),
    ("PATCH", "/v1/mnp/admin/persons/{person_id}/experiences/{row_id}"),
    ("DELETE", "/v1/mnp/admin/persons/{person_id}/experiences/{row_id}"),
    ("POST", "/v1/mnp/admin/persons/{person_id}/activities"),
    ("PATCH", "/v1/mnp/admin/persons/{person_id}/activities/{row_id}"),
    ("DELETE", "/v1/mnp/admin/persons/{person_id}/activities/{row_id}"),
    ("POST", "/v1/mnp/admin/persons/{person_id}/languages"),
    ("PATCH", "/v1/mnp/admin/persons/{person_id}/languages/{row_id}"),
    ("DELETE", "/v1/mnp/admin/persons/{person_id}/languages/{row_id}"),
    ("GET", "/v1/mnp/me/person"),
    ("POST", "/v1/mnp/me/person"),
    ("POST", "/v1/mnp/me/person/activate"),
    ("GET", "/v1/mnp/me/person/skills/search"),
    ("POST", "/v1/mnp/me/person/skills"),
    ("DELETE", "/v1/mnp/me/person/skills/{row_id}"),
    ("POST", "/v1/mnp/me/person/educations"),
    ("PATCH", "/v1/mnp/me/person/educations/{row_id}"),
    ("DELETE", "/v1/mnp/me/person/educations/{row_id}"),
    ("POST", "/v1/mnp/me/person/credentials"),
    ("PATCH", "/v1/mnp/me/person/credentials/{row_id}"),
    ("DELETE", "/v1/mnp/me/person/credentials/{row_id}"),
    ("POST", "/v1/mnp/me/person/experiences"),
    ("PATCH", "/v1/mnp/me/person/experiences/{row_id}"),
    ("DELETE", "/v1/mnp/me/person/experiences/{row_id}"),
    ("POST", "/v1/mnp/me/person/activities"),
    ("PATCH", "/v1/mnp/me/person/activities/{row_id}"),
    ("DELETE", "/v1/mnp/me/person/activities/{row_id}"),
    ("POST", "/v1/mnp/me/person/languages"),
    ("PATCH", "/v1/mnp/me/person/languages/{row_id}"),
    ("DELETE", "/v1/mnp/me/person/languages/{row_id}"),
    ("POST", "/v1/mnp/me/person/cv"),
    ("POST", "/v1/mnp/me/person/cv/confirm"),
}


def _current_routes() -> set[tuple[str, str]]:
    routes = set()
    for route in app.routes:
        path = getattr(route, "path", None)
        methods = getattr(route, "methods", None)
        if path is None or not methods or path in _FRAMEWORK_ROUTES:
            continue
        for method in methods:
            if method == "HEAD":
                continue
            routes.add((method, path))
    return routes


def test_api_route_table_matches_frozen_snapshot():
    current = _current_routes()
    missing = EXPECTED_ROUTES - current
    added = current - EXPECTED_ROUTES
    assert not missing, f"routes removed or renamed since the snapshot was frozen: {sorted(missing)}"
    assert not added, (
        f"new routes not yet reflected in the frozen snapshot: {sorted(added)}. "
        "If this is an intentional API change, update EXPECTED_ROUTES in this file."
    )
