"""Generate docs/data_explorer/ONET_DATA_DICTIONARY.md and
ESCO_DATA_DICTIONARY.md straight from the built reference DB, so they can
never drift from what was actually loaded.
"""

from __future__ import annotations

import sqlite3
import textwrap

from data_explorer import config
from data_explorer.io import log

_HEADER = "<!-- GENERATED by `python -m data_explorer.cli dictionary` — do not edit by hand -->\n"
_ESSENTIAL_SQL = "SELECT count(*) FROM esco_occupation_skill WHERE relation_type = 'essential'"


def _conn() -> sqlite3.Connection:
    if not config.REFERENCE_DB.exists():
        raise SystemExit("reference.sqlite not built — run: python -m data_explorer.cli build")
    return sqlite3.connect(config.REFERENCE_DB)


def _table_report(cur, table: str, note: str = "") -> str:
    cols = [r[1] for r in cur.execute(f"PRAGMA table_info({table})")]
    (n,) = cur.execute(f"SELECT count(*) FROM {table}").fetchone()  # noqa: S608
    out = [f"### `{table}` — {n:,} rows", ""]
    if note:
        out += [note, ""]
    out += ["| column | example |", "|---|---|"]
    sample = cur.execute(f"SELECT * FROM {table} LIMIT 1").fetchone()  # noqa: S608
    for i, c in enumerate(cols):
        ex = "" if sample is None else str(sample[i])
        if len(ex) > 70:
            ex = ex[:67] + "…"
        out.append(f"| `{c}` | {ex.replace('|', '\\|')} |")
    out.append("")
    return "\n".join(out)


def write_onet() -> None:
    conn = _conn()
    cur = conn.cursor()
    parts = [
        _HEADER,
        "# O*NET DATA DICTIONARY (as loaded into the DATA EXPLORER reference DB)\n",
        f"Source: **O*NET {config.ONET_RELEASE.replace('_', '.')}** bulk text database "
        f"(+ **O*NET 30.2** `Work Values.txt` only). Licence **CC BY 4.0**.\n",
        "> This documents the *subset* of O*NET loaded for research. It is a faithful, "
        "filtered transcription — no value is altered, interpreted, or AI-reconstructed. "
        "`raw_value` is O*NET's own number; `normalized_value` is a plain linear rescale of "
        "that scale's official [min,max] to [0,1] and is `NULL` for category/percentage/rank "
        "scales. A missing value is an **absent row**, never 0.\n",
        "## Scales (verbatim from `Scales Reference.txt`)\n",
        "| scale_id | name | min | max | [0,1]-normalised? |",
        "|---|---|---|---|---|",
    ]
    norm = set(config.ONET_SCALE_RANGES)
    for sid, name, lo, hi in cur.execute("SELECT scale_id, scale_name, minimum, maximum FROM onet_scale ORDER BY scale_id"):
        parts.append(f"| `{sid}` | {name} | {lo:g} | {hi:g} | {'yes' if sid in norm else 'no (raw only)'} |")
    parts.append("")

    parts.append("## Rating families in `onet_rating` (brief §7 — ALL dimensions, not just what MNP selects)\n")
    parts.append("| table_key | Content Model family | scales | distinct elements | occupations covered |")
    parts.append("|---|---|---|---|---|")
    for tk, fam, sids, ne, no in cur.execute(
        "SELECT table_key, family, group_concat(DISTINCT scale_id), "
        "count(DISTINCT element_id), count(DISTINCT soc) FROM onet_rating GROUP BY table_key ORDER BY table_key"
    ):
        parts.append(f"| `{tk}` | {fam} | {sids} | {ne} | {no:,} |")
    parts += ["",
              f"O*NET Work Styles: **{cur.execute('SELECT count(DISTINCT element_id) FROM onet_rating WHERE table_key=?', ('work_style',)).fetchone()[0]} elements** loaded "
              f"(MNP matching currently selects {len(config.MNP_SELECTED_ONET['work_style'])} — see "
              "`findings/WORK_STYLE_DIFFERENTIATION_FINDING_V1.md`).", ""]

    parts.append("## Tables\n")
    for t, note in [
        ("onet_occupation", "One row per O*NET-SOC 2019 occupation."),
        ("onet_occupation_title", "primary / alternate (`Job Titles.txt`) / reported (`Sample of Reported Titles.txt`) — the title corpus used for crosswalk suggestion."),
        ("onet_rating", "The unified numeric picture — every family above. RAW + normalized distinct."),
        ("onet_work_value", "6 O*NET Work Values (EX 1–7), from the **30.2** release."),
        ("onet_task", "Task Statements (Core / Supplemental)."),
        ("onet_task_rating", "Task importance / relevance / frequency (IM / RT / FT scales)."),
        ("onet_software_skill", "`Software Skills.txt` — technology categories + a workplace example + Hot Technology / In Demand flags."),
        ("onet_related_occupation", "`Related Occupations.txt` — relatedness tier + index."),
        ("onet_dwa", "GWA → IWA → DWA activity tree (`GWAs to IWAs to DWAs.txt`)."),
        ("onet_content_model", "The full O*NET taxonomy tree (element_id → name → description)."),
        ("onet_scale_anchor", "Level-scale anchor descriptions (`Level Scale Anchors.txt`)."),
        ("onet_category", "Category descriptions for RL / RW / … scales."),
    ]:
        try:
            parts.append(_table_report(cur, t, note))
        except sqlite3.OperationalError:
            pass
    conn.close()
    _write("ONET_DATA_DICTIONARY.md", "\n".join(parts))


def write_esco() -> None:
    conn = _conn()
    cur = conn.cursor()
    parts = [
        _HEADER,
        "# ESCO DATA DICTIONARY (as loaded into the DATA EXPLORER reference DB)\n",
        f"Source: **ESCO {config.ESCO_VERSION}** classification, CSV bundles, "
        f"languages **{' + '.join(config.ESCO_LANGUAGES)}** "
        "(Ukrainian produced by the European Training Foundation). Free of charge, open.\n",
        "> ESCO is a DATA EXPLORER research source only — **not** a runtime dependency of the "
        "production MNP engine (brief §8). Raw ESCO concept URIs are preserved verbatim; they "
        "are references, never MNP identity.\n",
        "## Concept counts\n",
        f"- occupations: **{cur.execute('SELECT count(*) FROM esco_occupation').fetchone()[0]:,}**",
        f"- skills / knowledge / competences: **{cur.execute('SELECT count(*) FROM esco_skill').fetchone()[0]:,}**",
        f"- ISCO groups: **{cur.execute('SELECT count(*) FROM esco_isco_group').fetchone()[0]:,}**",
        f"- occupation↔skill relations: **{cur.execute('SELECT count(*) FROM esco_occupation_skill').fetchone()[0]:,}** "
        f"({cur.execute(_ESSENTIAL_SQL).fetchone()[0]:,} essential)",
        "",
        "## Skill types & reuse levels\n",
        "| skill_type | count |  | reuse_level | count |",
        "|---|---|---|---|---|",
    ]
    st = cur.execute("SELECT skill_type, count(*) FROM esco_skill GROUP BY skill_type ORDER BY 2 DESC").fetchall()
    rl = cur.execute("SELECT reuse_level, count(*) FROM esco_skill GROUP BY reuse_level ORDER BY 2 DESC").fetchall()
    for i in range(max(len(st), len(rl))):
        a = st[i] if i < len(st) else ("", "")
        b = rl[i] if i < len(rl) else ("", "")
        parts.append(f"| {a[0]} | {a[1]:,} |  | {b[0]} | {b[1]:,} |" if isinstance(a[1], int) else f"| {a[0]} | {a[1]} |  | {b[0]} | {b[1]} |")
    parts.append("")
    parts.append("## Tables\n")
    for t, note in [
        ("esco_occupation", "ESCO occupation concepts. `preferred_label_en` + `preferred_label_uk` side by side; `isco_group` = 4-digit ISCO."),
        ("esco_occupation_label", "alt / hidden labels, per language — the alias corpus."),
        ("esco_skill", "skill / knowledge / competence concepts, `skill_type` + `reuse_level`."),
        ("esco_skill_label", "alt / hidden skill labels, per language."),
        ("esco_isco_group", "ISCO-08 groups (ESCO's occupation backbone; also the crosswalk key)."),
        ("esco_occupation_skill", "occupation ↔ skill, `relation_type` = essential | optional."),
        ("esco_skill_skill", "skill ↔ skill relations."),
        ("esco_broader", "broader/narrower for both pillars."),
        ("esco_skill_hierarchy", "skill taxonomy levels 0–3."),
    ]:
        try:
            parts.append(_table_report(cur, t, note))
        except sqlite3.OperationalError:
            pass
    conn.close()
    _write("ESCO_DATA_DICTIONARY.md", "\n".join(parts))


def _write(name: str, text: str) -> None:
    config.DOCS_DIR.mkdir(parents=True, exist_ok=True)
    (config.DOCS_DIR / name).write_text(text.rstrip() + "\n", encoding="utf-8")
    log(f"  wrote docs/data_explorer/{name}")


def write_all() -> None:
    write_onet()
    write_esco()
