"""Generate docs/data_explorer/SOURCE_DATA_INVENTORY.md from stg_source +
the reference DB (brief §9).
"""

from __future__ import annotations

import sqlite3

from data_explorer import config
from data_explorer.io import log

_HEADER = "<!-- GENERATED by `python -m data_explorer.cli inventory` — do not edit by hand -->\n"


def write() -> None:
    if not config.REFERENCE_DB.exists():
        raise SystemExit("reference.sqlite not built — run: python -m data_explorer.cli build")
    conn = sqlite3.connect(config.REFERENCE_DB)
    cur = conn.cursor()

    parts = [
        _HEADER,
        "# SOURCE DATA INVENTORY — MNP DATA EXPLORER V1\n",
        "Every external dataset loaded into `data/data_explorer/reference.sqlite`. "
        "All data is **downloaded** (never scraped) and its SHA-256 recorded. "
        "`data/` is gitignored — everything is reproducible with "
        "`python -m data_explorer.cli download && python -m data_explorer.cli build`.\n",
        "## Datasets\n",
        "| label | kind | version | official URL | file | sha256 | licence |",
        "|---|---|---|---|---|---|---|",
    ]
    for lbl, kind, ver, url, f, sha, lic in cur.execute(
        "SELECT source_label, kind, version, official_url, file, sha256, license FROM stg_source ORDER BY kind, source_label"
    ):
        parts.append(f"| `{lbl}` | {kind} | {ver} | {url} | `{f}` | `{(sha or '')[:16]}…` | {lic} |")
    parts.append("")

    parts.append("## Attribution (must be shown wherever this data reaches an end user)\n")
    for lbl, attr in cur.execute("SELECT source_label, attribution FROM stg_source ORDER BY source_label"):
        parts.append(f"- **{lbl}**: {attr}")
    parts.append("")

    parts.append("## Tables in reference.sqlite\n")
    parts.append("| table | rows | source | MNP potential use | currently used by MNP? |")
    parts.append("|---|---|---|---|---|")
    usage = {
        "onet_occupation": ("O*NET 31.0", "career catalogue backbone / crosswalk target", "candidate (5 alpha careers unmapped)"),
        "onet_occupation_title": ("O*NET 31.0", "alias / crosswalk-suggestion corpus", "no"),
        "onet_rating": ("O*NET 31.0", "RAW career dimensions: interests, ALL work styles, abilities, essential+transferable skills, knowledge, work activities, work context, education, T&E", "partial — matching selects ~4 work-style + 6 RIASEC + 6 work-context elements"),
        "onet_work_value": ("O*NET 30.2", "Values Fit career side (3 DIRECT keys)", "partial (prior workstream)"),
        "onet_task": ("O*NET 31.0", "Experience Transfer — task/function overlap", "no (not yet wired)"),
        "onet_task_rating": ("O*NET 31.0", "task importance weighting", "no"),
        "onet_software_skill": ("O*NET 31.0", "tools/technology requirements", "no"),
        "onet_related_occupation": ("O*NET 31.0", "Transition Distance / adjacency prior", "no"),
        "onet_dwa": ("O*NET 31.0", "detailed work-activity vocabulary", "no"),
        "onet_content_model": ("O*NET 31.0", "self-describing taxonomy", "n/a (metadata)"),
        "onet_scale": ("O*NET 31.0", "scale ranges for normalisation", "n/a (metadata)"),
        "esco_occupation": ("ESCO v1.2.1", "occupation enrichment, UA labels, ISCO backbone", "no (Explorer only, per Founder Decision #17)"),
        "esco_skill": ("ESCO v1.2.1", "skill/knowledge vocabulary, UA labels, transversal tagging", "no (Explorer only)"),
        "esco_occupation_skill": ("ESCO v1.2.1", "occupation↔skill (essential/optional) — MNP requirement candidates", "no (Explorer only)"),
        "esco_isco_group": ("ESCO v1.2.1", "ISCO bridge for crosswalk + UA classifier alignment", "no"),
        "xwalk_esco_onet": ("O*NET Resource Center", "official ESCO↔O*NET mapping — MnpExternalMapping candidates", "no (candidates for review)"),
    }
    for t in [r[0] for r in cur.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")]:
        (n,) = cur.execute(f"SELECT count(*) FROM {t}").fetchone()  # noqa: S608
        src, use, used = usage.get(t, ("—", "—", "—"))
        parts.append(f"| `{t}` | {n:,} | {src} | {use} | {used} |")
    conn.close()

    config.DOCS_DIR.mkdir(parents=True, exist_ok=True)
    (config.DOCS_DIR / "SOURCE_DATA_INVENTORY.md").write_text("\n".join(parts).rstrip() + "\n", encoding="utf-8")
    log("  wrote docs/data_explorer/SOURCE_DATA_INVENTORY.md")
