"""`python -m data_explorer.cli analysis` — writes:
  docs/data_explorer/DATA_QUALITY_REPORT.md
  docs/data_explorer/findings/WORK_STYLE_DIFFERENTIATION_FINDING_V1.md
"""

from __future__ import annotations

import sqlite3

from data_explorer import config
from data_explorer.analysis import dimensions, quality
from data_explorer.io import log


def _conn() -> sqlite3.Connection:
    if not config.REFERENCE_DB.exists():
        raise SystemExit("reference.sqlite not built — run: python -m data_explorer.cli build")
    return sqlite3.connect(config.REFERENCE_DB)


def _quality_md(conn) -> str:
    rep = quality.run(conn)
    parts = ["<!-- GENERATED by `python -m data_explorer.cli analysis` -->",
             "# DATA QUALITY REPORT — MNP DATA EXPLORER V1\n",
             "Read-only checks over `data/data_explorer/reference.sqlite`. "
             "A count > 0 on an `error` row should block using the DB for the Golden Dataset.\n",
             "| severity | check | count |", "|---|---|---|"]
    for row in rep.as_rows():
        parts.append(f"| {row['severity']} | {row['check']} | {row['count']:,} |")
    return "\n".join(parts) + "\n"


def _work_style_finding_md(conn) -> str:
    r = dimensions.work_style_full_vs_selected(conn)
    p = [
        "# METHODOLOGY_FINDING — Work Style differentiation (O*NET, brief §14)\n",
        "**Type:** research finding. **Raised by:** MNP DATA EXPLORER V1. "
        "**Date:** 2026-08-30. **Production code unchanged.**\n",
        "## FACTS\n",
        f"- O*NET 31.0 exposes **{r['n_all']} Work Style elements** (scale `WI`, −3…+3). "
        f"The prior MNP matching workstream selected **{r['n_selected']}** of them "
        f"(`leadership`, `initiative`, `ambiguity_tolerance`, + a `social`+`cooperation` composite).",
        "- A known problem (from the prior workstream's M4.6 pass): the 4-element MNP Work "
        "Style career vector often fails the guarded-cosine differentiation check — its "
        "spread across occupations is too small.\n",
        "## DATA — discriminative power (stdev of the normalised value across occupations)\n",
        f"| set | elements | mean coverage | mean discriminative power |",
        f"|---|---|---|---|",
        f"| ALL O*NET Work Styles | {r['n_all']} | {r['mean_coverage_all']} | **{r['mean_discriminative_power_all']}** |",
        f"| MNP-selected ({r['n_selected']}) | {r['n_selected']} | — | **{r['mean_discriminative_power_selected']}** |",
        f"| the other {r['n_all'] - r['n_selected']} | {r['n_all'] - r['n_selected']} | — | **{r['mean_discriminative_power_unselected']}** |",
        "",
        "### Most discriminative Work Style elements (across all occupations)\n",
        "| element | id | coverage | mean | stdev (discriminative power) | MNP-selected? |",
        "|---|---|---|---|---|---|",
    ]
    for s in r["most_discriminative"]:
        p.append(f"| {s.element_name} | `{s.element_id}` | {s.coverage} | {s.mean} | **{s.stdev}** | {'yes' if s.selected_by_mnp else 'no'} |")
    p += ["", "### Least discriminative\n",
          "| element | id | coverage | mean | stdev | MNP-selected? |", "|---|---|---|---|---|---|"]
    for s in r["least_discriminative"]:
        p.append(f"| {s.element_name} | `{s.element_id}` | {s.coverage} | {s.mean} | {s.stdev} | {'yes' if s.selected_by_mnp else 'no'} |")

    p += [
        "",
        "## RESULT\n",
        "The full Work Style table's mean discriminative power is "
        f"**{r['mean_discriminative_power_all']}**; the MNP-selected subset's is "
        f"**{r['mean_discriminative_power_selected']}**. "
        + ("The selected subset is **not** the most discriminative slice of the table."
           if (r['mean_discriminative_power_selected'] or 0) <= (r['mean_discriminative_power_all'] or 0)
           else "The selected subset is at least as discriminative as the table average."),
        "",
        "## INTERPRETATION\n",
        "O*NET Work Styles `WI` (impact-on-performance) values are compressed for most "
        "occupations — the domain genuinely does not separate jobs as strongly as Interests "
        "(`OI`) does. Adding elements helps only if the *added* elements carry spread.\n",
        "## OPTIONS\n",
        "1. Keep 4 elements; accept that Work Style Fit is often `INSUFFICIENT`/`LOW_DIFFERENTIATION` and lean on Interest + Feasibility.\n"
        "2. Expand the selected set to the most-discriminative elements above (data-driven, still O*NET-native).\n"
        "3. Use a per-family differentiation threshold tuned to each domain's real spread.\n"
        "4. Treat Work Style as a *secondary* signal only (consistent with Founder Decision #22 for RIASEC).\n",
        "## RECOMMENDATION\n",
        "Do **not** change the guard threshold or weights in production. Put options 2 + 3 in "
        "front of the Founder with this table. If expanding the set: prefer the elements marked "
        "'no' in *Most discriminative* above. Re-run this finding after any O*NET release bump.\n",
        "*(Generated from `data/data_explorer/reference.sqlite`. Rebuild + re-run: "
        "`python -m data_explorer.cli build && python -m data_explorer.cli analysis`.)*",
    ]
    return "\n".join(p) + "\n"


def run() -> None:
    conn = _conn()
    try:
        config.DOCS_DIR.mkdir(parents=True, exist_ok=True)
        (config.DOCS_DIR / "DATA_QUALITY_REPORT.md").write_text(_quality_md(conn), encoding="utf-8")
        log("  wrote docs/data_explorer/DATA_QUALITY_REPORT.md")
        (config.DOCS_DIR / "findings" / "WORK_STYLE_DIFFERENTIATION_FINDING_V1.md").write_text(
            _work_style_finding_md(conn), encoding="utf-8")
        log("  wrote docs/data_explorer/findings/WORK_STYLE_DIFFERENTIATION_FINDING_V1.md")
    finally:
        conn.close()
