"""CRM 1.0: clients, profiles, work experience, skills, languages, consultations, files, calls, tasks, timeline

Revision ID: 9d5a4e3bf954
Revises: 4fcd55c76e57
Create Date: 2026-08-20 15:04:52.720859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9d5a4e3bf954'
down_revision: Union[str, None] = '4fcd55c76e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('telegram_username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('source_channel', sa.Enum('TELEGRAM', 'PHONE', 'WEBSITE', 'APP', 'MANAGER', name='sourcechannel', native_enum=False), nullable=False),
    sa.Column('telegram_user_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('consultant_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'SCREENING', 'WAITING_CONSULTANT', 'CAREER_CONSULTATION', 'READY_FOR_MATCHING', 'IN_WORK', 'PAUSED', 'CLOSED', name='clientstatus', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('NORMAL', 'HIGH', 'URGENT', name='clientpriority', native_enum=False), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['consultant_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_user_id')
    )
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=False)
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('phonet_call_id', sa.String(length=128), nullable=True),
    sa.Column('direction', sa.Enum('INCOMING', 'OUTGOING', 'MISSED', name='calldirection', native_enum=False), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ANSWERED', 'MISSED', 'FAILED', name='callstatus', native_enum=False), nullable=False),
    sa.Column('recording_url', sa.String(length=1024), nullable=True),
    sa.Column('contact_type', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_client_id'), 'calls', ['client_id'], unique=False)
    op.create_table('career_consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('consultant_id', sa.Integer(), nullable=True),
    sa.Column('primary_target', sa.String(length=255), nullable=True),
    sa.Column('alternative_targets', sa.JSON(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('skills_gaps', sa.JSON(), nullable=True),
    sa.Column('search_strategy', sa.Text(), nullable=True),
    sa.Column('expectations_realistic', sa.String(length=64), nullable=True),
    sa.Column('expectations_comment', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['consultant_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', name='uq_career_consultation_client')
    )
    op.create_index(op.f('ix_career_consultations_client_id'), 'career_consultations', ['client_id'], unique=False)
    op.create_table('client_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.Enum('CV', 'COVER_LETTER', 'CERTIFICATE', 'DIPLOMA', 'PORTFOLIO', 'OTHER', name='filetype', native_enum=False), nullable=False),
    sa.Column('other_description', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('is_current_cv', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_files_client_id'), 'client_files', ['client_id'], unique=False)
    op.create_table('client_languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=True),
    sa.Column('can_work_in_it', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_languages_client_id'), 'client_languages', ['client_id'], unique=False)
    op.create_table('client_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('currently_employed', sa.Boolean(), nullable=True),
    sa.Column('current_position', sa.String(length=255), nullable=True),
    sa.Column('current_fields', sa.JSON(), nullable=True),
    sa.Column('current_income', sa.String(length=64), nullable=True),
    sa.Column('current_income_currency', sa.String(length=16), nullable=True),
    sa.Column('search_reasons', sa.JSON(), nullable=True),
    sa.Column('readiness_to_start', sa.String(length=128), nullable=True),
    sa.Column('readiness_date', sa.String(length=32), nullable=True),
    sa.Column('urgency', sa.String(length=64), nullable=True),
    sa.Column('nonstandard_info', sa.Text(), nullable=True),
    sa.Column('education_level', sa.String(length=128), nullable=True),
    sa.Column('specialty', sa.String(length=255), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('courses', sa.JSON(), nullable=True),
    sa.Column('driver_licenses', sa.JSON(), nullable=True),
    sa.Column('other_qualification', sa.Text(), nullable=True),
    sa.Column('primary_target', sa.String(length=255), nullable=True),
    sa.Column('alternative_targets', sa.JSON(), nullable=True),
    sa.Column('interesting_fields', sa.JSON(), nullable=True),
    sa.Column('avoid_fields', sa.JSON(), nullable=True),
    sa.Column('open_to_career_change', sa.String(length=32), nullable=True),
    sa.Column('min_salary', sa.String(length=64), nullable=True),
    sa.Column('desired_salary', sa.String(length=64), nullable=True),
    sa.Column('salary_currency', sa.String(length=16), nullable=True),
    sa.Column('employment_types', sa.JSON(), nullable=True),
    sa.Column('work_formats', sa.JSON(), nullable=True),
    sa.Column('schedules', sa.JSON(), nullable=True),
    sa.Column('work_cities', sa.JSON(), nullable=True),
    sa.Column('commute_limit', sa.String(length=64), nullable=True),
    sa.Column('relocation_ready', sa.String(length=32), nullable=True),
    sa.Column('relocation_cities', sa.JSON(), nullable=True),
    sa.Column('business_trips_ok', sa.String(length=32), nullable=True),
    sa.Column('start_date', sa.String(length=64), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('critical_constraint', sa.Boolean(), nullable=False),
    sa.Column('constraints_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_profiles_client_id'), 'client_profiles', ['client_id'], unique=True)
    op.create_table('client_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Enum('BASIC', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='skilllevel', native_enum=False), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_skills_client_id'), 'client_skills', ['client_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('other_description', sa.String(length=255), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DONE', 'CANCELLED', name='taskstatus', native_enum=False), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_client_id'), 'tasks', ['client_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'STATUS_CHANGED', 'ASSIGNED', 'CALL', 'FILE_UPLOADED', 'FILE_DELETED', 'PROFILE_FIELD_CHANGED', 'SCREENING_COMPLETED', 'CONSULTATION_COMPLETED', 'READY_FOR_MATCHING', 'NOTE', name='timelineeventtype', native_enum=False), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('before_value', sa.Text(), nullable=True),
    sa.Column('after_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_client_id'), 'timeline_events', ['client_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_created_at'), 'timeline_events', ['created_at'], unique=False)
    op.create_table('work_experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=True),
    sa.Column('start_month_year', sa.String(length=16), nullable=True),
    sa.Column('end_month_year', sa.String(length=16), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('achievements', sa.Text(), nullable=True),
    sa.Column('tools', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_experiences_client_id'), 'work_experiences', ['client_id'], unique=False)
    op.add_column('admin_users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('admin_users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.alter_column('admin_users', 'role',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('ADMIN', 'MANAGER', 'CAREER_CONSULTANT', name='adminrole', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_users', 'role',
               existing_type=sa.Enum('ADMIN', 'MANAGER', 'CAREER_CONSULTANT', name='adminrole', native_enum=False),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.drop_column('admin_users', 'is_active')
    op.drop_column('admin_users', 'full_name')
    op.drop_index(op.f('ix_work_experiences_client_id'), table_name='work_experiences')
    op.drop_table('work_experiences')
    op.drop_index(op.f('ix_timeline_events_created_at'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_client_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_tasks_client_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_client_skills_client_id'), table_name='client_skills')
    op.drop_table('client_skills')
    op.drop_index(op.f('ix_client_profiles_client_id'), table_name='client_profiles')
    op.drop_table('client_profiles')
    op.drop_index(op.f('ix_client_languages_client_id'), table_name='client_languages')
    op.drop_table('client_languages')
    op.drop_index(op.f('ix_client_files_client_id'), table_name='client_files')
    op.drop_table('client_files')
    op.drop_index(op.f('ix_career_consultations_client_id'), table_name='career_consultations')
    op.drop_table('career_consultations')
    op.drop_index(op.f('ix_calls_client_id'), table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
