import { type FormEvent, type ReactNode, useEffect, useMemo, useState } from "react";
import { Link, NavLink, Navigate, Outlet, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { adminLogin, adminRequest, personRequest, publicRequest, sessionStorageKeys } from "./api/client";
import { useAppDispatch, useAppSelector } from "./app/hooks";
import { signedIn, signedOut } from "./app/store";
import type { CareerListItem, Person, PersonCore, PersonListItem } from "./types";

const publicNav = [
  ["/how", "Як це працює"], ["/catalog", "Професії"],
  ["/region", "Регіон"], ["/about", "Про МОЖУ"],
] as const;

const icons: Record<string, ReactNode> = {
  route: <><circle cx="5.5" cy="15" r="2"/><circle cx="14.5" cy="5" r="2"/><path d="M7.4 14.2c4-1 5-3 5-6M12.5 7h-3M12.5 7v2.5"/></>,
  briefcase: <><rect x="3" y="6.5" width="14" height="10" rx="1.6"/><path d="M7.5 6.5V5.2c0-.8.6-1.4 1.4-1.4h2.2c.8 0 1.4.6 1.4 1.4v1.3M3 10.5h14"/></>,
  target: <><circle cx="10" cy="10" r="7"/><circle cx="10" cy="10" r="3.4"/><circle cx="10" cy="10" r=".6" fill="currentColor"/></>,
  compass: <><circle cx="10" cy="10" r="7.2"/><path d="M13.2 6.8 11.4 11l-4.2 1.8L9 8.6z"/></>,
  doc: <><path d="M6 3.5h5l3 3v10H6zM11 3.5v3h3M8 10h4M8 13h4"/></>,
  chart: <><path d="M4 4v12h12M7.5 13.5v-3M10.5 13.5V8M13.5 13.5V6"/></>,
  lightbulb: <><path d="M7 12.5a4.5 4.5 0 1 1 6 0c-.6.5-1 1.2-1 2h-4c0-.8-.4-1.5-1-2zM8.5 17.5h3"/></>,
  edit: <path d="M13.5 4.5 15.5 6.5 7 15l-3 .8.8-3z"/>,
  checklist: <><path d="M8 5.5h9M8 10h9M8 14.5h9M3.2 5l1.1 1.1L6.3 4M3.2 9.6l1.1 1.1L6.3 8.5M3.2 14.1l1.1 1.1 2-2.2"/></>,
  arrow: <path d="M4 10h11M11 6l4 4-4 4"/>,
  check: <path d="m4.5 10.5 3.5 3.5 7.5-8"/>,
  sparkles: <><path d="M10 3.5 11.4 8 16 9.4 11.4 10.8 10 15.5 8.6 10.8 4 9.4 8.6 8z"/><path d="M15 4v3M16.5 5.5h-3"/></>,
};
function Icon({name}:{name:string}){return <svg className="nv-i" viewBox="0 0 20 20" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden>{icons[name]||icons.doc}</svg>}
function LogoMark(){return <svg className="nv-logo-mark" viewBox="0 0 32 32" width="32" height="32" aria-hidden><rect width="32" height="32" rx="9" fill="#ffc72c"/><path d="M11 9l5 7 5-7M16 16v7" stroke="#18140f" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round" fill="none"/></svg>}
function Brand() {
  return <Link className="brand" to="/"><LogoMark/><span className="brand-copy"><strong>Yellow Hub</strong><small>Кар'єрний центр</small></span></Link>;
}

function PublicLayout() {
  return <div className="site">
    <header className="topbar"><Brand/><nav>{publicNav.map(([to, label]) => <NavLink key={to} to={to}>{label}</NavLink>)}<NavLink to="/market">Ринок праці</NavLink></nav>
      <div className="top-actions"><Link className="button ghost" to="/login">Увійти</Link><Link className="button small" to="/profile"><span className="desktop-label">Створити профіль</span><span className="mobile-label">Створити</span></Link></div>
    </header>
    <main className="page"><Outlet/></main>
    <footer><Brand/><nav><Link to="/about">Про МОЖУ</Link><Link to="/catalog">Професії</Link><Link to="/how">Як це працює</Link><Link to="/market">Ринок праці</Link></nav><span>© 2026 Yellow Hub</span></footer>
  </div>;
}

function Home() {
  return <>
    <section className="hero-split">
      <div className="hero-copy"><span className="eyebrow">Кар'єрний навігатор</span><h1>Знайдіть напрям, у якому <em>хочеться рухатись</em></h1>
        <p className="lead">Створіть кар'єрний профіль і побачите реалістичні професійні напрями, що вам підходять зараз.</p>
        <div className="hero-actions"><Link className="button large" to="/profile">Створити кар'єрний профіль →</Link><Link className="button secondary large" to="/catalog">Переглянути професії</Link></div>
        <div className="check-row">{["Безкоштовно","10–15 хвилин","Без реєстрації"].map(x=><span key={x}><i><Icon name="check"/></i>{x}</span>)}</div>
      </div>
      <div className="illus-wrap hero-visual"><div className="illus-frame"><PersonIllustration/></div><div className="visual-caption"><span><Icon name="sparkles"/></span><div><small>Ваш результат</small><strong>Зрозумілий кар'єрний план</strong></div></div>
      </div>
    </section>
    <section className="home-section audience"><div className="section-intro"><span>Для кого це</span><h2>Коли потрібен зрозумілий наступний крок</h2></div><div className="tile-nav-grid">{[["route","Хочу змінити професію"],["briefcase","Втратив(-ла) роботу"],["target","Повертаюсь на ринок праці"],["compass","Шукаю свій напрям"]].map(([i,t])=><Link className="tile-nav" to="/profile" key={t}><span className="tn-ico"><Icon name={i}/></span><b>{t}</b></Link>)}</div></section>
    <section className="home-section benefits"><div className="section-intro"><span>Результат</span><h2>Усе необхідне для впевненого рішення</h2><p>Не просто список професій, а зрозумілий профіль і послідовний план дій.</p></div><div className="tile-feat-grid">{[["doc","Кар'єрний профіль","Ваші сильні сторони та інтереси"],["chart","Реалістичні напрями","Професії, що вам підходять зараз"],["lightbulb","Зрозумілі пояснення","Чому саме ці професії і що це означає"],["target","Наступні кроки","З чого почати і як розвиватися"]].map(([i,t,d])=><article className="tile-feat" key={t}><span className="tn-ico"><Icon name={i}/></span><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></section>
    <section className="home-section process"><div className="section-intro"><span>Простий процес</span><h2>Від профілю до наступного кроку</h2></div><FlowSteps/></section>
    <CtaBand title="Почніть із першого кроку" text="Створіть кар'єрний профіль і відкрийте нові можливості для себе."/>
  </>;
}

function PersonIllustration(){return <svg viewBox="0 0 520 390" role="img" aria-label="Приклад кар'єрного профілю">
  <defs><linearGradient id="profileBg" x1="0" y1="0" x2="1" y2="1"><stop stopColor="#fff8df"/><stop offset="1" stopColor="#f6e9b9"/></linearGradient><filter id="cardShadow" x="-20%" y="-20%" width="140%" height="150%"><feDropShadow dx="0" dy="10" stdDeviation="12" floodColor="#594b1f" floodOpacity=".12"/></filter></defs>
  <rect width="520" height="390" rx="30" fill="url(#profileBg)"/>
  <circle cx="454" cy="55" r="76" fill="#ffc72c" opacity=".26"/><circle cx="36" cy="342" r="92" fill="#fff" opacity=".55"/>
  <g filter="url(#cardShadow)"><rect x="58" y="42" width="404" height="306" rx="24" fill="#fff"/></g>
  <rect x="58" y="42" width="404" height="62" rx="24" fill="#18140f"/><rect x="58" y="82" width="404" height="22" fill="#18140f"/>
  <circle cx="92" cy="73" r="13" fill="#ffc72c"/><path d="M87 68l5 6 5-6M92 74v6" stroke="#18140f" strokeWidth="2" strokeLinecap="round" fill="none"/>
  <text x="116" y="78" fill="#fff" fontSize="15" fontFamily="Manrope, sans-serif" fontWeight="700">Мій кар'єрний профіль</text><circle cx="428" cy="73" r="5" fill="#ffc72c"/>
  <circle cx="113" cy="148" r="25" fill="#ffe58f"/><circle cx="113" cy="141" r="8" fill="#18140f"/><path d="M97 169c2-13 9-20 16-20s14 7 16 20" fill="#18140f"/>
  <rect x="152" y="128" width="116" height="11" rx="5.5" fill="#18140f"/><rect x="152" y="148" width="78" height="8" rx="4" fill="#ddd8ca"/><rect x="152" y="166" width="98" height="8" rx="4" fill="#eeeae0"/>
  <rect x="314" y="124" width="112" height="47" rx="14" fill="#fff5cd"/><text x="329" y="144" fill="#7f6814" fontSize="9" fontFamily="Manrope, sans-serif" fontWeight="700">ПРОФІЛЬ ГОТОВИЙ</text><text x="329" y="160" fill="#18140f" fontSize="15" fontFamily="Manrope, sans-serif" fontWeight="800">82%</text>
  <text x="88" y="213" fill="#8b826d" fontSize="9" fontFamily="Manrope, sans-serif" fontWeight="700">ВАШІ СИЛЬНІ СТОРОНИ</text>
  <rect x="88" y="226" width="106" height="30" rx="15" fill="#fff2bd"/><text x="108" y="245" fill="#18140f" fontSize="10" fontFamily="Manrope, sans-serif" fontWeight="700">Комунікація</text><rect x="202" y="226" width="104" height="30" rx="15" fill="#f3f1eb"/><text x="224" y="245" fill="#18140f" fontSize="10" fontFamily="Manrope, sans-serif" fontWeight="700">Аналітика</text><rect x="314" y="226" width="104" height="30" rx="15" fill="#f3f1eb"/><text x="333" y="245" fill="#18140f" fontSize="10" fontFamily="Manrope, sans-serif" fontWeight="700">Креативність</text>
  <rect x="88" y="279" width="330" height="43" rx="13" fill="#f8f7f3"/><circle cx="111" cy="300" r="11" fill="#ffc72c"/><path d="m106 300 3 3 6-7" stroke="#18140f" strokeWidth="2" fill="none"/><text x="132" y="297" fill="#18140f" fontSize="10" fontFamily="Manrope, sans-serif" fontWeight="700">3 професійні напрями вже підібрано</text><text x="132" y="311" fill="#8b826d" fontSize="8" fontFamily="Manrope, sans-serif">На основі вашого досвіду та інтересів</text>
</svg>}
function FlowSteps(){return <div className="step-flow">{[["edit","Створіть профіль","Дайте відповіді на прості запитання"],["checklist","Отримайте напрями","Сервіс підбере професії, що вам підходять"],["target","Оберіть свій фокус","Дослідіть професії та можливості"],["chart","Рухайтесь далі","Отримайте наступні кроки для вашої мети"]].map(([i,t,d],n)=><div className="flow-group" key={t}><article className="sf-item"><div className="sf-row"><span className="sf-n">{n+1}</span><span className="sf-ico"><Icon name={i}/></span></div><h3>{t}</h3><p>{d}</p></article>{n<3&&<span className="sf-arrow"><Icon name="arrow"/></span>}</div>)}</div>}
function CtaBand({title,text}:{title:string;text:string}){return <div className="cta-band"><span className="cb-ico"><Icon name="sparkles"/></span><div><h2>{title}</h2><p>{text}</p></div><Link className="button large" to="/profile">Створити кар'єрний профіль →</Link><span className="cb-doodle">Ти можеш! ♥</span></div>}

function StaticPage({ title, intro, children }: { title: string; intro: string; children?: ReactNode }) {
  return <section className="narrow"><span className="eyebrow">YELLOW HUB · МОЖУ</span><h1>{title}</h1><p className="lead">{intro}</p>{children}</section>;
}

function How() { return <><section className="hero-split compact-hero"><div><span className="eyebrow">Ваш наступний крок — можливий</span><h1>Як це працює</h1><p className="lead">Ми зробили процес простим і зрозумілим, щоб ви могли отримати персональні рекомендації та обрати реалістичний наступний крок.</p></div><div className="illus-frame"><PersonIllustration/></div></section><FlowSteps/><CtaBand title="Готові зробити перший крок?" text="Створіть кар'єрний профіль і відкрийте нові можливості для себе."/></>; }
function About() { return <><StaticPage title="Про МОЖУ" intro="Соціальна програма в межах Yellow Hub, яка допомагає людям у складних життєвих ситуаціях знайти свій професійний шлях і повернутися до активного життя."/><div className="tile-feat-grid about-grid">{[["briefcase","Для тих, хто потребує підтримки"],["checklist","Безкоштовний доступ"],["edit","Експертна підтримка"],["lightbulb","Реальні можливості"]].map(([i,t])=><article className="tile-feat" key={t}><span className="tn-ico"><Icon name={i}/></span><h3>{t}</h3><p>Людська підтримка та зрозумілий наступний крок.</p></article>)}</div><CtaBand title="МОЖУ" text="Люди. Підтримка. Нові можливості."/></>; }
function Opportunities() { return <StaticPage title="Можливості" intro="Кар'єрні сценарії, вакансії та навчальні ресурси відкриватимуться поступово."><EmptyState title="Розділ готується" text="Ми не показуємо вигаданих вакансій або ринкових даних."/></StaticPage>; }
function Market(){return <StaticPage title="Ринок праці в Україні" intro="Актуальна інформація про тенденції, затребувані професії та навички на українському ринку праці."><EmptyState title="Незабаром" text="Ми готуємо для вас цей розділ."/><div className="tile-feat-grid">{[["chart","Тенденції"],["briefcase","Затребувані професії"],["target","Рівень зарплат"],["lightbulb","Навички майбутнього"]].map(([i,t])=><article className="tile-feat" key={t}><span className="tn-ico"><Icon name={i}/></span><h3>{t}</h3><p>Незабаром</p></article>)}</div></StaticPage>}
function Region(){return <StaticPage title="Професії у вашому регіоні" intro="Дізнайтеся, які професії найбільш затребувані у вашому регіоні, і які є можливості для працевлаштування та розвитку."><EmptyState title="Незабаром" text="Ми готуємо для вас цей розділ."/></StaticPage>}
function LoginInfo() { return <StaticPage title="Увійти" intro="Клієнти не потребують акаунта — кар'єрний профіль створюється без реєстрації. Цей вхід — для консультантів та адміністраторів Yellow Hub."><div className="login-split"><article className="login-role-card disabled"><span className="tn-ico"><Icon name="briefcase"/></span><h3>Я консультант</h3><p>Перегляд клієнтів, рекомендацій і статусів консультацій.</p><span className="button secondary">Увійти <small className="soon-tag">Незабаром</small></span></article><article className="login-role-card"><span className="tn-ico"><Icon name="checklist"/></span><h3>Я адміністратор</h3><p>Каталог професій, людей та повний доступ до налаштувань.</p><Link className="button" to="/admin/login">Увійти</Link></article></div></StaticPage>; }

function EmptyState({ title, text }: { title: string; text: string }) { return <div className="empty"><span>✦</span><h3>{title}</h3><p>{text}</p></div>; }
function Loading() { return <div className="loading">Завантаження…</div>; }
function ErrorBox({ message }: { message: string }) { return <div className="error">{message}</div>; }

function CareerCatalog() {
  const {id}=useParams(); const [items, setItems] = useState<CareerListItem[]>([]); const [error, setError] = useState(""); const [query, setQuery] = useState(""); const [category,setCategory]=useState("Усі");
  useEffect(() => { publicRequest<CareerListItem[]>("/careers").then(setItems).catch(e => setError(e.message)); }, []);
  if(id)return <CareerDetailPage id={id} items={items}/>;
  const categories=["Усі",...Array.from(new Set(items.map(x=>x.category_uk).filter((x):x is string=>!!x)))];
  const filtered = items.filter(x => (category==="Усі"||x.category_uk===category)&&`${x.name_uk} ${x.category_uk ?? ""} ${x.short_description_uk??""}`.toLowerCase().includes(query.toLowerCase()));
  return <section><div className="hero-split catalog-hero"><div><span className="eyebrow">Досліджуйте. Обирайте. Розвивайтесь</span><h1>Професії</h1><p className="lead">Досліджуйте світ професій, дізнавайтеся, чим вони займаються, та відкривайте нові можливості для свого майбутнього.</p><input className="search" placeholder="Пошук професії, навички або сфери діяльності" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="illus-wrap"><div className="illus-frame"><PersonIllustration/></div><div className="doodle"><span>↘</span> Відкривайте нові можливості</div></div></div>
    <div className="pill-row">{categories.map(x=><button className={category===x?"active":""} onClick={()=>setCategory(x)} key={x}>{x}</button>)}</div>{error && <ErrorBox message={error}/>} {!items.length && !error ? <Loading/> : filtered.length?<div className="pcard-grid">{filtered.map((x,i)=><Link className="pcard" to={`/catalog/${x.id}`} key={x.id}><div className={`pcard-illus tone-${i%3}`}><PersonIllustration/></div><div className="pcard-body"><h3>{x.name_uk}</h3><p>{x.short_description_uk || x.category_uk || "Перегляньте опис професії та ключові вимоги."}</p><span><Icon name="arrow"/></span></div></Link>)}</div>:<EmptyState title="Нічого не знайдено" text="Спробуйте інший запит або категорію."/>}<CtaBand title="Не знайшли потрібну професію?" text="Каталог поповнюється. Спробуйте інший запит або перегляньте всі категорії."/>
  </section>;
}
function CareerDetailPage({id,items}:{id:string;items:CareerListItem[]}){const [data,setData]=useState<Record<string,any>|null>(null);const [error,setError]=useState("");const [tab,setTab]=useState("about");useEffect(()=>{publicRequest<Record<string,any>>(`/careers/${id}`).then(setData).catch(e=>setError(e.message))},[id]);if(error)return <ErrorBox message={error}/>;if(!data)return <Loading/>;const identity=data.identity||{},overview=data.overview||{},responsibilities=data.responsibilities||[],skills=data.skills||{hard:[],soft:[]};return <section><div className="crumb"><Link to="/">Головна</Link><span>›</span><Link to="/catalog">Професії</Link><span>›</span><b>{identity.name_uk}</b></div><div className="hero-split detail-hero"><div><h1>{identity.name_uk}</h1><p className="lead">{overview.short_description_uk}</p></div><div className="illus-frame"><PersonIllustration/></div></div><div className="detail-tabs">{[["about","Про професію"],["skills","Навички"],["education","Освіта і розвиток"],["market","Ринок праці"],["related","Схожі професії"]].map(([k,t])=><button className={tab===k?"active":""} onClick={()=>setTab(k)} key={k}>{t}</button>)}</div>{tab==="about"&&<div className="detail-grid"><article className="panel"><h2>Про професію</h2><p>{overview.long_description_uk||"Розгорнутий опис готується."}</p></article><article className="panel"><h2>Що ви робитимете</h2><ul>{responsibilities.slice(0,4).map((r:Record<string,unknown>,i:number)=><li key={i}>{String(r.title_uk||"")}</li>)}</ul><Link className="button" to="/profile">Перевірити, чи підходить мені →</Link></article></div>}{tab==="skills"&&<div className="panel"><h2>Навички</h2><div className="skill-chips">{[...(skills.hard||[]),...(skills.soft||[])].map((s:Record<string,unknown>,i:number)=><span key={i}>{String(s.name_uk||"")}</span>)}</div></div>}{tab==="education"&&<EmptyState title="Освіта і розвиток" text="Перегляньте вимоги та типовий шлях входу у професію."/>}{tab==="market"&&<EmptyState title="Дані ринку будуть додані пізніше" text="Ми не показуємо орієнтовних цифр без перевіреного джерела."/>}{tab==="related"&&<div className="pcard-grid">{items.filter(x=>x.id!==id).slice(0,3).map(x=><Link className="pcard" to={`/catalog/${x.id}`} key={x.id}><div className="pcard-body"><h3>{x.name_uk}</h3><p>{x.category_uk}</p></div></Link>)}</div>}</section>}

function ProfileStart() { return <StaticPage title="Створити кар'єрний профіль" intro="Оберіть зручний спосіб, і ми допоможемо вам зробити перший крок до нових можливостей."><div className="choice-grid"><Link className="choice featured" to="/profile/edit"><span className="recommend"><Icon name="sparkles"/> Рекомендовано</span><span className="tn-ico"><Icon name="edit"/></span><b>Заповнити самостійно</b><span>Підійде, якщо готові пройти профіль за 10–15 хвилин.</span></Link><Link className="choice" to="/profile/cv"><span className="tn-ico"><Icon name="doc"/></span><b>Завантажити резюме</b><span>Ми проаналізуємо ваш досвід і допоможемо швидше заповнити профіль.</span></Link><div className="choice disabled"><span className="tn-ico"><Icon name="briefcase"/></span><b>Профіль створює консультант <small className="soon-tag">Незабаром</small></b><span>Отримайте особисту підтримку від нашого фахівця.</span></div></div></StaticPage>; }

const wizardSteps=["Основне","Досвід","Освіта","Навички","Мови","Сертифікати","Активності","Мобільність","Перевірка"];
function ProfileWizard(){const nav=useNavigate();const [step,setStep]=useState(0);const [person,setPerson]=useState<Person|null>(null);const [core,setCore]=useState<Partial<PersonCore>>({first_name:""});const [error,setError]=useState("");useEffect(()=>{personRequest<Person>("/me/person").then(p=>{setPerson(p);setCore(p.core)}).catch(e=>{if(e.status!==404)setError(e.message)})},[]);const saveCore=async()=>{const p=await personRequest<Person>("/me/person",{method:"POST",body:JSON.stringify(core)});setPerson(p);setCore(p.core)};const next=async()=>{try{setError("");if(step===0)await saveCore();if(step===wizardSteps.length-1){await personRequest("/me/person/activate",{method:"POST"});nav("/profile/confirmed");return}setStep(x=>x+1)}catch(e){setError((e as Error).message)}};const lists:Record<number,[string,unknown[]]|undefined>={1:["Досвід роботи",person?.experiences||[]],2:["Освіта",person?.educations||[]],3:["Навички та інструменти",person?.skills||[]],4:["Мови",person?.languages||[]],5:["Сертифікати",person?.credentials||[]],6:["Проєкти та активності",person?.activities||[]],7:["Мобільність",person?[person.mobility]:[]]};return <section className="wizard-wrap"><div className="wizard-top"><span>Створення кар'єрного профілю</span><b>Крок {step+1} з {wizardSteps.length}</b></div><div className="wizard-track"><i style={{width:`${((step+1)/wizardSteps.length)*100}%`}}/></div><h1>{wizardSteps[step]}</h1>{step===0&&<div className="wizard-card"><div className="avatar">{`${core.first_name?.[0]||""}${core.last_name?.[0]||""}`.toUpperCase()||"?"}</div><div className="form form-grid">{[["first_name","Ім'я *"],["last_name","Прізвище"],["phone","Телефон"],["email","Email"],["telegram_username","Telegram (@username)"],["city","Місто"],["region","Область"]].map(([key,label])=><label key={key}><span>{label}</span><input required={key==="first_name"} value={String(core[key as keyof PersonCore]??"")} onChange={e=>setCore({...core,[key]:e.target.value})}/></label>)}</div></div>}{lists[step]&&<WizardFacts title={lists[step]![0]} rows={lists[step]![1]}/>} {step===8&&<div className="wizard-card review-card"><span className="review-check"><Icon name="check"/></span><h2>Чудово! Основна інформація готова</h2><p>Ви заповнили ключові розділи профілю. Далі ми дізнаємось більше про ваші сильні сторони, інтереси та цілі.</p>{wizardSteps.slice(0,5).map((x,i)=><div className="review-row" key={x}><Icon name={i===0||((lists[i]?.[1].length||0)>0)?"check":"doc"}/>{x}</div>)}</div>}{error&&<ErrorBox message={error}/>}<div className="wizard-nav">{step>0&&<button className="button secondary" onClick={()=>setStep(x=>x-1)}>Назад</button>}<button className="button" onClick={()=>void next()}>{step===8?"Зберегти профіль":"Продовжити →"}</button></div></section>}
function WizardFacts({title,rows}:{title:string;rows:unknown[]}){return <div className="wizard-card"><p className="muted">{rows.length?`Додано записів: ${rows.length}`:"Поки що порожньо. Це нормально — розділ можна заповнити пізніше."}</p>{rows.map((row,i)=><div className="wizard-fact" key={i}><span className="tn-ico"><Icon name="doc"/></span><b>{String((row as Record<string,unknown>).raw_job_title||(row as Record<string,unknown>).institution_name||(row as Record<string,unknown>).raw_input||(row as Record<string,unknown>).language||(row as Record<string,unknown>).title||title)}</b></div>)}</div>}

function ProfileEdit() {
  const [person, setPerson] = useState<Person | null>(null); const [core, setCore] = useState<Partial<PersonCore>>({ first_name: "" }); const [error,setError]=useState(""); const [saved,setSaved]=useState(false);
  useEffect(()=>{personRequest<Person>("/me/person").then(p=>{setPerson(p);setCore(p.core)}).catch(e=>{if(e.status!==404)setError(e.message)});},[]);
  const save=async(e:FormEvent)=>{e.preventDefault();setError("");setSaved(false);try{const p=await personRequest<Person>("/me/person",{method:"POST",body:JSON.stringify(core)});setPerson(p);setCore(p.core);setSaved(true);}catch(err){setError((err as Error).message)}};
  return <StaticPage title="Основна інформація" intro="Почніть з контактів. Інші блоки можна доповнювати поступово."><form className="panel form" onSubmit={save}><div className="form-grid">{[["first_name","Ім'я *"],["last_name","Прізвище"],["phone","Телефон"],["email","Email"],["telegram_username","Telegram"],["city","Місто"],["region","Область"],["country","Країна"]].map(([key,label])=><label key={key}><span>{label}</span><input required={key==="first_name"} value={String(core[key as keyof PersonCore]??"")} onChange={e=>setCore({...core,[key]:e.target.value})}/></label>)}</div><label><span>Нотатки</span><textarea rows={4} value={core.notes??""} onChange={e=>setCore({...core,notes:e.target.value})}/></label>{error&&<ErrorBox message={error}/>} {saved&&<div className="success">Дані збережено</div>}<button className="button" type="submit">Зберегти профіль</button>{person&&<Link className="button secondary" to="/profile/me">Переглянути профіль</Link>}</form></StaticPage>;
}

function MyProfile() {
  const [person,setPerson]=useState<Person|null>(null);const [error,setError]=useState("");useEffect(()=>{personRequest<Person>("/me/person").then(setPerson).catch(e=>setError(e.message));},[]);
  if(error)return <ErrorBox message={error}/>; if(!person)return <Loading/>; const c=person.core;
  return <section><div className="page-title"><div><span className="eyebrow">DIGITAL CAREER PROFILE</span><h1>{c.first_name} {c.last_name}</h1><p>{c.city||"Місто не вказано"} · {c.status_uk||"Чернетка"}</p></div><Link className="button" to="/profile/edit">Редагувати</Link></div><div className="profile-grid"><FactCard title="Контакти" rows={[c.phone,c.email,c.telegram_username]}/><FactCard title="Досвід" rows={person.experiences.map(x=>String(x.raw_job_title||"Досвід"))}/><FactCard title="Освіта" rows={person.educations.map(x=>String(x.institution_name||x.education_level_uk||"Освіта"))}/><FactCard title="Навички" rows={person.skills.map(x=>String(x.raw_input||x.proficiency_uk||"Навичка"))}/><FactCard title="Мови" rows={person.languages.map(x=>`${x.language||""} · ${x.level_uk||""}`)}/><FactCard title="Документи" rows={person.documents.map(x=>String(x.filename||"Документ"))}/></div></section>;
}
function FactCard({title,rows}:{title:string;rows:(unknown|null|undefined)[]}){const clean=rows.filter(Boolean);return <article className="card"><h3>{title}</h3>{clean.length?<ul>{clean.map((r,i)=><li key={i}>{String(r)}</li>)}</ul>:<p className="muted">Поки немає даних</p>}</article>}

function CvUpload(){const [state,setState]=useState("");const upload=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const input=e.currentTarget.elements.namedItem("cv") as HTMLInputElement;if(!input.files?.[0])return;const body=new FormData();body.append("file",input.files[0]);setState("Обробляємо файл…");try{await personRequest("/me/person/cv",{method:"POST",body});setState("Файл завантажено. Наступним кроком буде перевірка знайдених даних.")}catch(err){setState((err as Error).message)}};return <StaticPage title="Завантажте ваше резюме" intro="Підтримуються PDF, DOC і DOCX до 10 МБ."><form className="upload" onSubmit={upload}><input name="cv" type="file" accept=".pdf,.doc,.docx" required/><button className="button">Обробити резюме</button>{state&&<p>{state}</p>}</form></StaticPage>}

const workspaceItems=[["/app","Огляд"],["/app/profile","Кар'єрний профіль"],["/app/scenarios","Сценарії"],["/app/route","Маршрут"],["/app/vacancies","Вакансії"],["/app/progress","Прогрес"]] as const;
function WorkspaceLayout(){return <div className="workspace"><aside><Brand/><nav>{workspaceItems.map(([to,l])=><NavLink end={to==="/app"} key={to} to={to}>{l}{!["/app","/app/profile"].includes(to)&&<small>Незабаром</small>}</NavLink>)}</nav><Link to="/">← На головну</Link></aside><main><Outlet/></main></div>}
function WorkspaceHome(){return <section><span className="eyebrow">МІЙ ПРОСТІР</span><h1>Ваш наступний крок</h1><div className="panel"><h2>Завершіть кар'єрний профіль</h2><p>Додайте факти про досвід, освіту та навички — вони стануть основою майбутніх рекомендацій.</p><Link className="button" to="/profile/edit">Доповнити профіль</Link></div></section>}
function Future({name}:{name:string}){return <section><h1>{name}</h1><EmptyState title="Незабаром" text="Функціональність ще не підключена до реальних даних."/></section>}

function RequireAdmin(){const token=useAppSelector(s=>s.auth.adminToken);return token?<Outlet/>:<Navigate to="/admin/login" replace/>}
function AdminLogin(){const dispatch=useAppDispatch();const nav=useNavigate();const [error,setError]=useState("");const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{const data=await adminLogin(String(fd.get("email")),String(fd.get("password")));dispatch(signedIn({token:data.access_token,email:data.email}));nav("/admin/persons");}catch(err){setError((err as Error).message)}};return <div className="login-page"><div className="login-card"><Brand/><span className="eyebrow">CONSULTANT WORKSPACE</span><h1>Вхід консультанта</h1><p>Увійдіть, щоб працювати з клієнтами та їхніми профілями.</p><form onSubmit={submit}><label><span>Email</span><input name="email" type="email" defaultValue="admin@mnp.local" required/></label><label><span>Пароль</span><input name="password" type="password" required/></label>{error&&<ErrorBox message={error}/>}<button className="button wide">Увійти</button></form><Link to="/">← Повернутися на сайт</Link></div></div>}

function AdminLayout(){const dispatch=useAppDispatch();const nav=useNavigate();return <div className="admin-shell"><aside><Brand/><span className="side-label">CONSULTANT WORKSPACE</span><nav><NavLink to="/admin/persons">Мої клієнти</NavLink><NavLink to="/admin/persons/new">Створити клієнта</NavLink><NavLink to="/admin/catalog">Career KB</NavLink></nav><button className="link-button" onClick={()=>{dispatch(signedOut());nav("/admin/login")}}>Вийти</button></aside><main><Outlet/></main></div>}

function PersonList(){const [items,setItems]=useState<PersonListItem[]>([]);const [error,setError]=useState("");const [query,setQuery]=useState("");useEffect(()=>{adminRequest<PersonListItem[]>("/admin/persons").then(setItems).catch(e=>setError(e.message));},[]);const filtered=useMemo(()=>items.filter(x=>`${x.name} ${x.phone} ${x.email} ${x.city}`.toLowerCase().includes(query.toLowerCase())),[items,query]);return <section><div className="page-title"><div><span className="eyebrow">PERSON KB</span><h1>Мої клієнти</h1><p>Єдина база профілів для роботи консультанта.</p></div><Link className="button" to="/admin/persons/new">+ Створити клієнта</Link></div><input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Пошук за ім'ям, телефоном, email або містом"/>{error&&<ErrorBox message={error}/>}<div className="table-wrap"><table><thead><tr><th>Клієнт</th><th>Телефон</th><th>Email</th><th>Місто</th><th>Статус</th><th>Оновлено</th><th/></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><b>{p.name||"Без імені"}</b><small>{p.telegram_username}</small></td><td>{p.phone||"—"}</td><td>{p.email||"—"}</td><td>{p.city||"—"}</td><td><span className={`status ${p.status}`}>{p.status_uk}</span></td><td>{p.updated_at?.slice(0,10)||"—"}</td><td><Link className="button secondary small" to={`/admin/persons/${p.id}`}>Відкрити</Link></td></tr>)}</tbody></table>{!filtered.length&&!error&&<EmptyState title="Клієнтів не знайдено" text="Змініть пошук або створіть нового клієнта."/>}</div></section>}

function PersonCreate(){const nav=useNavigate();const [error,setError]=useState("");const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{const p=await adminRequest<Person>("/admin/persons",{method:"POST",body:JSON.stringify({first_name:String(fd.get("first_name")),last_name:String(fd.get("last_name")||"")})});nav(`/admin/persons/${p.id}`)}catch(err){setError((err as Error).message)}};return <section className="narrow"><span className="eyebrow">НОВИЙ КЛІЄНТ</span><h1>Створити профіль</h1><form className="panel form" onSubmit={submit}><label><span>Ім'я *</span><input name="first_name" required autoFocus/></label><label><span>Прізвище</span><input name="last_name"/></label>{error&&<ErrorBox message={error}/>}<button className="button">Створити та відкрити</button></form></section>}

const detailTabs=["Основне","Освіта","Досвід","Активності","Навички","Мови","Документи","Мобільність"];
function PersonDetail(){const {id}=useParams();const [person,setPerson]=useState<Person|null>(null);const [core,setCore]=useState<Partial<PersonCore>>({first_name:""});const [tab,setTab]=useState("Основне");const [error,setError]=useState("");const [saved,setSaved]=useState(false);const load=()=>adminRequest<Person>(`/admin/persons/${id}`).then(p=>{setPerson(p);setCore(p.core)}).catch(e=>setError(e.message));useEffect(()=>{void load()},[id]);const save=async(e:FormEvent)=>{e.preventDefault();setSaved(false);try{const p=await adminRequest<Person>(`/admin/persons/${id}`,{method:"PATCH",body:JSON.stringify(core)});setPerson(p);setCore(p.core);setSaved(true)}catch(err){setError((err as Error).message)}};if(error&&!person)return <ErrorBox message={error}/>;if(!person)return <Loading/>;const collections:Record<string,[string,unknown[]]>={"Освіта":["educations",person.educations],"Досвід":["experiences",person.experiences],"Активності":["activities",person.activities],"Навички":["skills",person.skills],"Мови":["languages",person.languages],"Документи":["documents",person.documents]};return <section><div className="page-title"><div><Link className="back" to="/admin/persons">← Мої клієнти</Link><h1>{person.core.first_name} {person.core.last_name}</h1><p>ID: {person.id}</p></div><span className={`status ${person.core.status}`}>{person.core.status_uk}</span></div><div className="tabs">{detailTabs.map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{tab==="Основне"&&<form className="panel form" onSubmit={save}><div className="form-grid">{[["first_name","Ім'я *"],["last_name","Прізвище"],["phone","Телефон"],["email","Email"],["telegram_username","Telegram"],["city","Місто"],["region","Область"],["country","Країна"],["date_of_birth","Дата народження"]].map(([key,label])=><label key={key}><span>{label}</span><input type={key==="date_of_birth"?"date":"text"} required={key==="first_name"} value={String(core[key as keyof PersonCore]??"")} onChange={e=>setCore({...core,[key]:e.target.value})}/></label>)}</div><label><span>Нотатки консультанта</span><textarea rows={5} value={core.notes??""} onChange={e=>setCore({...core,notes:e.target.value})}/></label>{saved&&<div className="success">Зміни збережено. Дані залишаться після перезавантаження.</div>}<button className="button">Зберегти</button><button className="button secondary" type="button" onClick={()=>void load()}>Перезавантажити</button></form>}{collections[tab]&&<CollectionView title={tab} rows={collections[tab][1]}/>} {tab==="Мобільність"&&<CollectionView title="Мобільність і формат роботи" rows={[person.mobility]}/>}</section>}
function CollectionView({title,rows}:{title:string;rows:unknown[]}){return <div className="panel"><div className="page-title compact"><div><h2>{title}</h2><p>Факти з канонічного профілю MnpPerson.</p></div></div>{rows.length?<div className="fact-list">{rows.map((row,i)=><pre key={i}>{JSON.stringify(row,null,2)}</pre>)}</div>:<EmptyState title="Даних поки немає" text="Редагування цього блоку буде перенесене в наступній ітерації."/>}</div>}

function AdminCatalog(){const [items,setItems]=useState<CareerListItem[]>([]);const [error,setError]=useState("");useEffect(()=>{adminRequest<CareerListItem[]>("/admin/careers").then(setItems).catch(e=>setError(e.message));},[]);return <section><div className="page-title"><div><span className="eyebrow">CAREER KB</span><h1>База професій</h1><p>Канонічні професії ICAN. Дані не дублюються.</p></div></div>{error&&<ErrorBox message={error}/>}<div className="cards careers">{items.slice(0,150).map(x=><article className="card" key={x.id}><span className={`status ${x.status}`}>{x.status||"draft"}</span><h3>{x.name_uk}</h3><p>{x.category_uk||x.code}</p></article>)}</div></section>}

export function App(){return <Routes><Route element={<PublicLayout/>}><Route index element={<Home/>}/><Route path="how" element={<How/>}/><Route path="about" element={<About/>}/><Route path="opportunities" element={<Opportunities/>}/><Route path="market" element={<Market/>}/><Route path="region" element={<Region/>}/><Route path="login" element={<LoginInfo/>}/><Route path="catalog" element={<CareerCatalog/>}/><Route path="catalog/:id" element={<CareerCatalog/>}/><Route path="profile" element={<ProfileStart/>}/><Route path="profile/build" element={<ProfileWizard/>}/><Route path="profile/edit" element={<ProfileEdit/>}/><Route path="profile/me" element={<MyProfile/>}/><Route path="profile/cv" element={<CvUpload/>}/><Route path="profile/confirmed" element={<MyProfile/>}/></Route><Route path="app" element={<WorkspaceLayout/>}><Route index element={<WorkspaceHome/>}/><Route path="profile" element={<MyProfile/>}/><Route path=":module" element={<Future name="Розділ у розробці"/>}/></Route><Route path="admin/login" element={<AdminLogin/>}/><Route element={<RequireAdmin/>}><Route path="admin" element={<AdminLayout/>}><Route index element={<Navigate to="persons" replace/>}/><Route path="persons" element={<PersonList/>}/><Route path="persons/new" element={<PersonCreate/>}/><Route path="persons/:id" element={<PersonDetail/>}/><Route path="catalog" element={<AdminCatalog/>}/></Route></Route><Route path="*" element={<Navigate to="/" replace/>}/></Routes>}
